language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  local-dir: docs
  repo: amazingandyyy/pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  target-branch: gh-pages
  name: TravisCI Helper